.TH DRM_INFO: "1" "June 2020" "drm_info" "User Commands"
.SH NAME
drm_info \- Dump information about DRM devices
.SH SYNOPSIS
\fBdrm_info\fR
[\fB-j\fR] [\fB--\fR] [\fBpath\fR]
.SH DESCRIPTION
drm_info is used to dump information about DRM
devices, planes, encoders, crtcs, planes and their DRM properties
.SH OPTIONS
.TP
\fB\-\j\fR
Output in json format
.SH AUTHOR
Scott Anderson <scott@anderso.nz>
