#ifndef TABLES_H
#define TABLES_H

#include <stdint.h>

/* The implementation of these functions are generated by fourcc.py */

const char *format_str(uint32_t format);
const char *basic_modifier_str(uint64_t modifier);

#endif
